version: "3.7"

services:
  app:
    build: .
    ports:
      - "3000" # Expose the port for the app

  Nginx:
    image: nginx
    ports:
      - "80:80" # Expose port 80 for Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount nginx.conf file
    depends_on:
      - a
